### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by Suntrie** [Nats15555/java#1]
<s>1. Бинарные файлы с расширением *.class под контроль git класть не стоит - они являются производными от файлов исходного кода. Уже выложенные - стоит удалить (git rm);
2. Скорректируйте, пожалуйста, содержимое pom.xml. Вам действительно нужно такое количество дублей одной и той же зависимости?</s>

**Comment by Nats15555** [comment]
1)удалил
2)да дубликаты удалил) даже не заметил что идея их так наплодила

**Comment by Suntrie** [comment]
3. Program удалите, пожалуйста. Он Вам никак не нужен

**Comment by Nats15555** [comment]
удалил
