### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [Nats15555/java#2]
<s>1. Поскольку Вы разрабатываете, по сути, библиотеку - как для файла User, так и для файла PhoneBook нужно добавить перегрузку стандартных методов equals/ hashCode/ toString. Первое и последнее поможет в тестировании, второе нужно для нормальной работы коллекций типа HashMap с элементами;

2. Добавление пользователя - добавление не имени, а пользователя (User newUser) целиком, аналогично с удалением пользователя;</s>

3. Для поиска индекса элемента в строке существует стандартный метод indexOf. Как правило, стандартные методы будут являться оптимизированной версией логики, написанной Вами, и, если они существуют, стоит пользоваться именно ими. Аналогично полезным может быть (и будет) метод contains. **Upd.** Здесь речь идёт о методе https://docs.oracle.com/javase/8/docs/api/java/util/List.html#indexOf-java.lang.Object- . Это минорный комментарий, но, возможно, с учётом того, как именно функционирует разработанная Вами телефонная книга с точки зрения дубликатов имён, equals User стоит переопределить только для имён.

<s>4. Кажется, что в заметном числе методов логично было бы различать ситуации логической невозможности осуществить требуемое действие (возврат false) и ситуацию, когда методом некорректно воспользовались (выбрасываем исключение).</s>

<s>5. Мы с Вами уже обсуждали интерфейсы и реализацию -  в публичных методах и при определении полей лучше (дешевле с точки зрения потенциальной переработки кода + принято) пользоваться первыми. **Upd.** См. User -> getUserNumber + новый комментарий 1;</s>

<s>6. Нужны ли с точки зрения работы со ссылочным типом данных в коде вызовы 
` this.users.get(indexUser).setUserNumber(buffNum);`
или без них можно обойтись? **Upd** - здесь имелось в виду, что нет необходимости переопределять коллекцию целиком (вроде, было через переприсваивание списка), если Вы получили коллекцию, лежащую внутри User геттером, можно просто user.getCollection.add("555");</s>

7. <s>Для того, чтобы не получить проблем с NPE на this.users - можно изначально его инициализировать пустым списком и проверять, что в конструктор Вам не пытаются передать null.  **Upd.** На сеттеры самого User здесь, видимо, тоже стоит посмотреть.</s>

_____

<s>8. ` return new User("", empty);` - лучше воспользоваться `Optional<User> userOptional = Optional.empty();` (стандартный вариант решения аналогичных задач)</s>
<s>9. Кажется, пока что-то пошло не совсем так с выбрасыванием исключений (Идея не должна их подсвечивать серым). Чем отличаются checked/ unchecked? Кто из них должен указываться под throws? Какой из видов нужен Вам в рамках решения Вашей задачи по разработке библиотечного класса? **Upd.** В секции ` throws Exception ` обычно перечисляют конкретные виды выбрасываемых исключений, иначе есть шанс получить непредусмотренное исключение, например, и обработать его также, как Вы бы обработали предусмотренное. Непроверяемые исключения (те, для которых не требуется написание блока catch, подробнее можно посмотреть, например, здесь - https://javarush.ru/groups/posts/1944-iskljuchenija-checked-unchecked-i-svoi-sobstvennihe) не требуют и секции throws;</s>

10. Текстовые константы обычно выносят в виде переменных с модификаторами public static final в начало класса (и переиспользуют несколько раз), так проще читать и легче вносить изменения (minor)

**Comment by Nats15555** [comment]
1)переопределил
2)добавил
3)у меня это не иcпользуетcя
4)добавил иcключения
5)это неудобно, я могу добавить конечно, но оно же не будет илюcтрировать полную работу, а true, false показывает точно  показывает cрабатал метод или нет, а на иcключения еcть иcключения
6)да можно без этого оботиcь я изменил(у меня теперь не индекc возвращаетcя а cразу юзер по этому иcпользовать это не надо теперь)
7)проинициализровал, как вы и cказали вcе норм и еще в некоторых меcтах тоже обрабатываю NPE где оно возникало

**Comment by Suntrie** [comment]
3. Должно (читаемость - и это глобальное требование при работе в проектах на N тысяч строк кода, эффективность)
4. Пока отчасти, см. вопросы выше
5. Можно пример, где Вам мешает использование List вместо ArrayList?

**Comment by Nats15555** [comment]
Я тут запуталcя в пунктах) поcтаралcя вcе учеcть.

**Comment by Suntrie** [comment]
Новые пункты (старые либо зачеркну, либо добавлю подпункты **upd**)

<s>1. Если немного дальше порефлексировать, то, с точки зрения гибкости использования разработанного библиотечного класса, лучшим решением таки является объявление поля не как ArrayList, а просто как List, тогда в конструктор можно класть любую реализацию и реально с Вашим кодом будет работать любая, реализующая интерфейс List - и LinkedList можно будет передавать при создании объекта класса в конструктор, и ArrayList, и CopyOnWriteList, и даже самописную реализацию интерфейса - при желании;</s> **Upd.** Приводить переданный List к ArrayList не требуется (и без проверки на то, что он им и является, это могло бы привести к ошибкам; проверить можно с помощью instanceOf, но это "антипаттерн", привязывание к конкретной реализации; если Вам нужен только List, его и стоит использовать - помимо тех мест, где без реализации нельзя обойтись, типа инициализации поля; Частично описывается вторым пунктом [здесь](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B8%D0%BD%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8_%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B5%D0%B9))
2. По предшествующему пункту 7 - прошу прощенья, но я, похоже, Вас несколько запутала. Здесь есть несколько подпунктов, на самом деле:        `this.userNumber = (ArrayList<String>) userNumber; ` - вот так делать, даже если userNumber <> null, нехорошо - у нас ссылочный тип данных, и, если Вы передаёте внутрь объекта класса ссылку на внешнюю коллекцию, снаружи её кто угодно может менять как угодно. Решение - копировать переданные объекты и сохранять их в локальную коллекцию. По проблеме с NPE в принципе - есть следующие варианты: использовать аннотации @Nullable / @NotNull или подобные (будут полезны разработчику-клиенту, управляются его настройками, посмотреть можно, например, здесь: https://docs.google.com/document/d/1IvuaGTQyAPiriVDFSpM0Foosm0R9cYMuHYNFwRWRb1k/edit - п.1, 3,  либо кастомизировать выбрасываемое исключение (просто падаем в процессе работы программы, скорее всего, т.к. логичнее делать исключение непроверяемым, поскольку оно не предполагает обработки в блоке catch программы-клиента).

**Comment by Suntrie** [comment]
3. Повторяющиеся проверки лучше вынести в служебные приватные функции.

**Comment by Suntrie** [comment]
2. Из delNumber и addNumber в текущей версии, на самом деле, как минимум, легко выносится вспомогательная функция
3.  Для методов типа foundNumbers обычно возвращают коллекцию номеров (чем более специализированный ТД, требующий меньше парсинга при использовании применяется, тем лучше - полученный сплошной текст можно только вывести, а список строк - как-то дополнительно обработать - например, банально посчитать количество номеров)
