### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Suntrie** [Nats15555/java#3]
<s>1. Сделайте, пожалуйста, так, чтобы в тестах были задействованы equals методы реализованных классов</s>

**Comment by Nats15555** [comment]
1) Реализовал

**Comment by Suntrie** [comment]
2. Тестовое покрытие не только PhoneBook, но и User должно быть порядка  80% (Run with code coverage)

**Comment by Nats15555** [comment]
Доработал, показывает 80+ на оба
